/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karma03
 */
@SuppressWarnings("serial")
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        
        phome.setBorder(BorderFactory.createMatteBorder(0, 0, 10, 0, new Color(102,0,102)));
        phome.setBackground(new Color(219, 190, 218));
        pvente.setBackground(new Color(240, 240, 240));
        pdettes.setBackground(new Color(240, 240, 240));
        pclient.setBackground(new Color(240, 240, 240));
        pfournisseur.setBackground(new Color(240, 240, 240));
        particle.setBackground(new Color(240, 240, 240));
        ppersonnel.setBackground(new Color(240, 240, 240));
        pdashboard.setBackground(new Color(240, 240, 240));
        panmenu.setBackground(new Color(240, 240, 240));
        panbar.setBackground(new Color(240, 240, 240));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param pclt
     */
    @SuppressWarnings("unchecked")
    //fonctions
    public void changePanel(JPanel pclt){
    pantochange.removeAll();
    pantochange.add(pclt);
    pantochange.repaint();
    pantochange.revalidate();
    }
    void setColor(JPanel chgColor){
        chgColor.setBackground(new Color(219, 190, 218));
        chgColor.setBorder(BorderFactory.createMatteBorder(0, 0, 10, 0, new Color(102,0,102)));
    }
    void resetColor(JPanel chgColor){
       chgColor.setBackground(new Color(240,240,240));
       chgColor.setBorder(null);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panbar = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pantochange = new javax.swing.JPanel();
        panhome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bacpic = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panmenu = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        iconHome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pvente = new javax.swing.JPanel();
        iconVente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pclient = new javax.swing.JPanel();
        iconClient = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pfournisseur = new javax.swing.JPanel();
        iconFournisseur = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        particle = new javax.swing.JPanel();
        iconProduit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ppersonnel = new javax.swing.JPanel();
        iconPersonnel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pdashboard = new javax.swing.JPanel();
        iconArchitecure = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pdettes = new javax.swing.JPanel();
        iconDettes = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_window_48px.png"))); // NOI18N
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        panbar.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 30, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_up_24px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        panbar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Easy Kivu Manager System");
        panbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 450, 30));

        getContentPane().add(panbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 30));

        pantochange.setLayout(new java.awt.BorderLayout());

        panhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        panhome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EASY - KIVU");
        panhome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TO");
        panhome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 40, 30));

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (425).jpg"))); // NOI18N
        panhome.add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, 1700, 590));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panhome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        pantochange.add(panhome, java.awt.BorderLayout.CENTER);

        getContentPane().add(pantochange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 910, 470));

        panmenu.setForeground(new java.awt.Color(153, 0, 153));
        panmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_page_48px.png"))); // NOI18N
        iconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconHomeMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HOME");

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconHome)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(phomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 80));

        iconVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sell_stock_48px.png"))); // NOI18N
        iconVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconVenteMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VENTE");

        javax.swing.GroupLayout pventeLayout = new javax.swing.GroupLayout(pvente);
        pvente.setLayout(pventeLayout);
        pventeLayout.setHorizontalGroup(
            pventeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pventeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(iconVente)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pventeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pventeLayout.setVerticalGroup(
            pventeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pventeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconVente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panmenu.add(pvente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 80));

        iconClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/client_management_48px.png"))); // NOI18N
        iconClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconClientMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CLIENTS");

        javax.swing.GroupLayout pclientLayout = new javax.swing.GroupLayout(pclient);
        pclient.setLayout(pclientLayout);
        pclientLayout.setHorizontalGroup(
            pclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pclientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconClient)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pclientLayout.setVerticalGroup(
            pclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(pclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 80));

        iconFournisseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop_48px.png"))); // NOI18N
        iconFournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconFournisseurMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PROVIDER");

        javax.swing.GroupLayout pfournisseurLayout = new javax.swing.GroupLayout(pfournisseur);
        pfournisseur.setLayout(pfournisseurLayout);
        pfournisseurLayout.setHorizontalGroup(
            pfournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfournisseurLayout.createSequentialGroup()
                .addGroup(pfournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfournisseurLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconFournisseur)
                        .addGap(19, 19, 19))
                    .addGroup(pfournisseurLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(124, 124, 124))
        );
        pfournisseurLayout.setVerticalGroup(
            pfournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfournisseurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(pfournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, 80));

        iconProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product_48px.png"))); // NOI18N
        iconProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconProduitMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PRODUITS");

        javax.swing.GroupLayout particleLayout = new javax.swing.GroupLayout(particle);
        particle.setLayout(particleLayout);
        particleLayout.setHorizontalGroup(
            particleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(particleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, particleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconProduit)
                .addGap(24, 24, 24))
        );
        particleLayout.setVerticalGroup(
            particleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(particleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(particle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 100, 80));

        iconPersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/member_48px.png"))); // NOI18N
        iconPersonnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPersonnelMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AGENTS");

        javax.swing.GroupLayout ppersonnelLayout = new javax.swing.GroupLayout(ppersonnel);
        ppersonnel.setLayout(ppersonnelLayout);
        ppersonnelLayout.setHorizontalGroup(
            ppersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppersonnelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconPersonnel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ppersonnelLayout.setVerticalGroup(
            ppersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(ppersonnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 100, 80));

        iconArchitecure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hierarchy_48px.png"))); // NOI18N
        iconArchitecure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconArchitecureMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ADMINS");

        javax.swing.GroupLayout pdashboardLayout = new javax.swing.GroupLayout(pdashboard);
        pdashboard.setLayout(pdashboardLayout);
        pdashboardLayout.setHorizontalGroup(
            pdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdashboardLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(iconArchitecure)
                .addGap(25, 25, 25))
            .addGroup(pdashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pdashboardLayout.setVerticalGroup(
            pdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconArchitecure, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panmenu.add(pdashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 90, 80));

        iconDettes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/debt_48px.png"))); // NOI18N
        iconDettes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconDettesMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DETTES");

        javax.swing.GroupLayout pdettesLayout = new javax.swing.GroupLayout(pdettes);
        pdettes.setLayout(pdettesLayout);
        pdettesLayout.setHorizontalGroup(
            pdettesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdettesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(iconDettes)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdettesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pdettesLayout.setVerticalGroup(
            pdettesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdettesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconDettes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        panmenu.add(pdettes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 80));

        getContentPane().add(panmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 930, 80));

        setSize(new java.awt.Dimension(907, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Voluez-vous vraiment vous deconnecter?","Deconnexion",
        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
        Connexion open = new Connexion();
        Accueil.super.dispose();
        open.setVisible(true); }
        
        
    }//GEN-LAST:event_closeMouseClicked

    private void iconVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconVenteMouseClicked
        setColor(pvente);  
        resetColor(pdettes);  
        resetColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelVente());

    }//GEN-LAST:event_iconVenteMouseClicked

    private void iconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconHomeMouseClicked
        resetColor(pvente); 
        resetColor(pdettes);
        setColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(panhome);
    }//GEN-LAST:event_iconHomeMouseClicked

    private void iconClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconClientMouseClicked
        resetColor(pvente); 
        resetColor(pdettes);
        resetColor(phome);
        setColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelClient());
    }//GEN-LAST:event_iconClientMouseClicked

    private void iconFournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFournisseurMouseClicked
        resetColor(pvente); 
        resetColor(pdettes);
        resetColor(phome);
        resetColor(pclient);
        setColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelFournisseur());
    }//GEN-LAST:event_iconFournisseurMouseClicked

    private void iconProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconProduitMouseClicked
        resetColor(pvente);  
        resetColor(pdettes);
        resetColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        setColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelArticle());
    }//GEN-LAST:event_iconProduitMouseClicked

    private void iconPersonnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPersonnelMouseClicked
        resetColor(pvente);
        resetColor(pdettes);
        resetColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        setColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelPersonnel());
    }//GEN-LAST:event_iconPersonnelMouseClicked

    private void iconArchitecureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconArchitecureMouseClicked
        resetColor(pvente); 
        resetColor(pdettes);
        resetColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        setColor(pdashboard);
        changePanel(new panelArchitecture());
    }//GEN-LAST:event_iconArchitecureMouseClicked

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        if(JOptionPane.showConfirmDialog(null, "Voluez-vous vraiment quitter ce programme?","Quitter",
            JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
                System.exit(0);
         }
    }//GEN-LAST:event_close1MouseClicked

    private void iconDettesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconDettesMouseClicked
        resetColor(pvente);  
        setColor(pdettes);  
        resetColor(phome);
        resetColor(pclient);
        resetColor(pfournisseur);
        resetColor(particle);
        resetColor(ppersonnel);
        resetColor(pdashboard);
        changePanel(new panelDettes());
    }//GEN-LAST:event_iconDettesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel iconArchitecure;
    private javax.swing.JLabel iconClient;
    private javax.swing.JLabel iconDettes;
    private javax.swing.JLabel iconFournisseur;
    private javax.swing.JLabel iconHome;
    private javax.swing.JLabel iconPersonnel;
    private javax.swing.JLabel iconProduit;
    private javax.swing.JLabel iconVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panbar;
    private javax.swing.JPanel panhome;
    private javax.swing.JPanel panmenu;
    private javax.swing.JPanel pantochange;
    private javax.swing.JPanel particle;
    private javax.swing.JPanel pclient;
    private javax.swing.JPanel pdashboard;
    private javax.swing.JPanel pdettes;
    private javax.swing.JPanel pfournisseur;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel ppersonnel;
    private javax.swing.JPanel pvente;
    // End of variables declaration//GEN-END:variables
}
