/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

/**
 *
 * @author karma03
 */
public class Chargement extends javax.swing.JFrame {

    /**
     * Creates new form Chargement
     */
    public Chargement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtloader = new javax.swing.JLabel();
        txtcounter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bacpic = new javax.swing.JLabel();
        objprogressbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtloader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtloader.setForeground(new java.awt.Color(102, 0, 102));
        txtloader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtloader.setText("Chargement...");
        getContentPane().add(txtloader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 30));

        txtcounter.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txtcounter.setForeground(new java.awt.Color(102, 0, 102));
        txtcounter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtcounter.setText(".");
        getContentPane().add(txtcounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EasyKivu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 130, 310, 50));

        bacpic.setForeground(new java.awt.Color(102, 0, 102));
        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (2).PNG"))); // NOI18N
        getContentPane().add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, 1310, 910));
        getContentPane().add(objprogressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        setSize(new java.awt.Dimension(803, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chargement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       Chargement well = new Chargement();
        well.setVisible(true);
        well.setOpacity((float) 0.8);
        
        try
        {
            for (int i = 1; i <= 100; i++)
            {
                Thread.sleep(20);
                well.objprogressbar.setValue(i);
                well.txtcounter.setText(""+i+"%");
                if(i==0)
                {
                    well.txtloader.setText(""+"Chargement...");
                    
                }
                else if(i==10)
                {
                    well.txtloader.setText(""+"Chargement..");
               
                }
                else if(i==20)
                {
                    well.txtloader.setText(""+"Chargement.");
                    
                }
                else if(i==30)
                {
                    well.txtloader.setText(""+"Chargement..");
                    
                }
                else if(i==40)
                {
                    well.txtloader.setText(""+"Chargement...");
                    
                }
                else if(i==50)
                {
                    well.txtloader.setText(""+"Chargement..");
                    
                }
                else if(i==60)
                {
                    well.txtloader.setText(""+"Chargement.");
                    
                }
                else if(i==70)
                {
                    well.txtloader.setText(""+"Chargement..");
                    
                }
                else if(i==80)
                {
                    well.txtloader.setText(""+"Chargement...");
                    
                }
                else if(i==90)
                {
                    well.txtloader.setText(""+"Chargement..");
                    
                }
                else if(i==95)
                {
                    well.txtloader.setText(""+"Chargement...");
                    
                }
                
            }
        }
        catch (Exception e)
        { 
            System.err.println(e);
        }
        Connexion open = new Connexion();
        well.setVisible(false);
        open.setVisible(true);
        well.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar objprogressbar;
    private javax.swing.JLabel txtcounter;
    private javax.swing.JLabel txtloader;
    // End of variables declaration//GEN-END:variables
}
