/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
@SuppressWarnings("serial")
public class panelArchitecture extends javax.swing.JPanel {

    /**
     * Creates new form panelClient
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();

    /**
     *
     */
    public panelArchitecture() {
        initComponents();
        panclient.setBackground(new Color(255,255,255,200));
        panother.setBackground(new Color(255,255,255,50));
        panbtns.setBackground(new Color(102,0,102,200));
        
        model.addColumn("Id");
        model.addColumn("Poste");
        model.addColumn("Description");

        table.setRowHeight(30);
        table.setShowGrid(true);
        table.setGridColor(new Color(102,0,102));
        table.setSelectionBackground(new Color(102,0,102));
        
        
        try{
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from architecture");
        while(Rs.next()){
        model.addRow(new Object[]{
           Rs.getString("id"),
           Rs.getString("poste"),
           Rs.getString("description"),
           });
           }
        }
        catch(Exception e){
        System.err.println(e);
        }
        table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //fonctions
    private void ajouter(){
        String post = txtposte.getText();
        String desc = txtdesc.getText();
        String requete = "insert into architecture(poste,description) VALUES ('"+
        post+"','"+
        desc+"')";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Le poste a été bien ajouté");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
}
    private void search(){
     try{
        String [] col = {"Id","Poste", "Description"};
        String [] aff = new String[3];
        DefaultTableModel mod= new DefaultTableModel(null, col);
        stm = conn.obtenirconnexion().createStatement();
        String search = txtsearch.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from architecture where id like '%"+search+"%' or poste like '%"+search+"%' or description like '%"+search+"%'");
            while(Rs.next()){
              aff[0] = Rs.getString("id");
              aff[1] = Rs.getString("poste");
              aff[2] = Rs.getString("description");
              mod.addRow(aff);
            }
            table.setModel(mod);
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelArchitecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refresh(){
        txtposte.setText("");
        txtdesc.setText("");
        txtid.setText("");
        txtsearch.setText("");
    }
    
    private void supprimer(){
        try{
            
            if(JOptionPane.showConfirmDialog(null, "Attention, voulez-vous vraiment faire cette opération de suppression?", "Suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0){
                stm.executeUpdate("Delete From architecture where id = "+txtid.getText());
                afficher();
                JOptionPane.showMessageDialog(null, "Le poste a été bien suprimé");
            }
            afficher();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }
    }
    
    private void modifier(){
    try{
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","Modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            stm.executeUpdate(
                    "UPDATE architecture SET poste='"
                    +txtposte.getText()+
                    "',description='"+txtdesc.getText()+
                    "' WHERE id="+txtid.getText()
                );
            afficher();
        }
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            afficher();
        }
}
private void afficher(){
 try{
        model.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from architecture");
        while(Rs.next())
        {
            model.addRow(new Object[]{
                Rs.getString("id"),
                Rs.getString("poste"),
                Rs.getString("description")}
            );
        }
        }
        catch(Exception e){
            System.err.println(e);
        }
        table.setModel(model);
}
private void deplace(int i){
   try{
     txtid.setText(model.getValueAt(i, 0).toString());
     txtposte.setText(model.getValueAt(i, 1).toString());
     txtdesc.setText(model.getValueAt(i, 2).toString());
     
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panclient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panbtns = new javax.swing.JPanel();
        btnupdate = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JLabel();
        btnrefresh1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtposte = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panother = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bacpic = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1460, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panclient.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("ARCHITECTURE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("POSTE");

        panbtns.setBackground(new java.awt.Color(102, 0, 102));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_48.png"))); // NOI18N
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_48.png"))); // NOI18N
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_refresh_48.png"))); // NOI18N
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });

        btnrefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_48.png"))); // NOI18N
        btnrefresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefresh1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnsLayout = new javax.swing.GroupLayout(panbtns);
        panbtns.setLayout(panbtnsLayout);
        panbtnsLayout.setHorizontalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnrefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panbtnsLayout.setVerticalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("ID");

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(102, 0, 102));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 0, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("RECHERCHER");

        txtposte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtposte.setForeground(new java.awt.Color(102, 0, 102));

        txtdesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(102, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("DESCRIPTION");

        javax.swing.GroupLayout panclientLayout = new javax.swing.GroupLayout(panclient);
        panclient.setLayout(panclientLayout);
        panclientLayout.setHorizontalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panclientLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panclientLayout.createSequentialGroup()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdesc)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panclientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtposte)
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 112, Short.MAX_VALUE))))
                            .addComponent(panbtns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsearch)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panclientLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panclientLayout.setVerticalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtposte, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panbtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 310));

        panother.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VERY EASY, VERY SPEED");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EASY KIVU");

        javax.swing.GroupLayout panotherLayout = new javax.swing.GroupLayout(panother);
        panother.setLayout(panotherLayout);
        panotherLayout.setHorizontalGroup(
            panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panotherLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
        );
        panotherLayout.setVerticalGroup(
            panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(panother, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 290, 110));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 570, 420));

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (425).jpg"))); // NOI18N
        add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, 1700, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       try
        {
            int i=table.getSelectedRow();deplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tableMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        modifier();
        afficher();
        refresh();
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        supprimer();
        afficher();
        refresh();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        refresh();
        afficher();
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btnrefresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefresh1MouseClicked
        ajouter();
        afficher();
        refresh();
    }//GEN-LAST:event_btnrefresh1MouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        search();
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel btnrefresh;
    private javax.swing.JLabel btnrefresh1;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panbtns;
    private javax.swing.JPanel panclient;
    private javax.swing.JPanel panother;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtposte;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
