/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

import com.onbarcode.barcode.Codabar;
import com.onbarcode.barcode.IBarcode;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
@SuppressWarnings("serial")
public class panelVente extends javax.swing.JPanel {

    /**
     * Creates new form panelClient
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();

    /**
     *
     */
    public panelVente() {
        initComponents();
        panclient.setBackground(new Color(255,255,255,200));
        panbtns.setBackground(new Color(102,0,102,200));
        
        model.addColumn("Id");
        model.addColumn("Client");
        model.addColumn("Fournisseur");
        model.addColumn("Article");
        model.addColumn("Description");
        model.addColumn("Prix");
        model.addColumn("Date");
        table.setRowHeight(30);
        table.setShowGrid(true);
        table.setGridColor(new Color(102,0,102));
        table.setSelectionBackground(new Color(102,0,102));
        
        
        try{
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from vventes");
        while(Rs.next()){
        model.addRow(new Object[]{
           Rs.getString("id"),
           Rs.getString("nom"),
           Rs.getString("thenom"),
           Rs.getString("designation"),
           Rs.getString("description"),
           Rs.getString("prix"),
           Rs.getString("dateV")
           });
           }
        }
        catch(Exception e){
        System.err.println(e);
        }
        table.setModel(model);
        searchun();
        searchdeux();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //fonctions
    private void ajouter(){
        String clt = txtidclient.getText();
        String art = txtidarticle.getText();
        String requete = "insert into ventes(refclient,refarticle,dateV) VALUES ('"+
        clt+"','"+
        art+"',now())";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "La vente a été bien faite");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
}
    
    
    private void refresh(){
        txtidarticle.setText("");
        txtclient.setText("");
        txtproduit.setText("");
        txtid.setText("");
        txtdesc.setText("");
        txtidclient.setText("");
        rsearchun();
        rsearchdeux();
        searchun();
        searchdeux();
    }
    
    private void supprimer(){
        try{
            
            if(JOptionPane.showConfirmDialog(null, "Attention, voulez-vous vraiment faire cette opération de suppression?", "Suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0){
                stm.executeUpdate("Delete From ventes where id = "+txtid.getText());
                afficher();
                JOptionPane.showMessageDialog(null, "La vente a été bien suprimée");
            }
            afficher();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }
    }
    
    private void modifier(){
    try{
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","Modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            stm.executeUpdate(
                    "UPDATE ventes SET refarticle='"
                    +txtidarticle.getText()+
                    "', refclient='"
                    +txtclient.getText()+
                    "' WHERE id="+txtid.getText()
                );
            afficher();
        }
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            afficher();
        }
}
private void afficher(){
 try{
        model.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from vventes");
        while(Rs.next())
        {
            model.addRow(new Object[]{
                Rs.getString("id"),
                Rs.getString("nom"),
                Rs.getString("thenom"),
                Rs.getString("designation"),
                Rs.getString("description"),
                Rs.getString("prix"),
                Rs.getString("dateV")
            }
            );
        }
        }
        catch(Exception e){
            System.err.println(e);
        }
        table.setModel(model);
}
private void mysearch(){
     try{
        String [] col = {"Id","Client", "Fournisseur", "Artilce", "Description", "Prix", "Date"};
        String [] aff = new String[7];
        DefaultTableModel mod= new DefaultTableModel(null, col);
        stm = conn.obtenirconnexion().createStatement();
        String search = txtsearch.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from vventes where "
                + "id like '%"+search+"%' "
                + "or nom like '%"+search+"%' "
                + "or thenom like '%"+search+"%' "
                + "or designation like '%"+search+"%' "
                + "or description like '%"+search+"%' "
                + "or prix like '%"+search+"%' "
                + "or dateV like '%"+search+"%' ");
            while(Rs.next()){
              aff[0] = Rs.getString("id");
              aff[1] = Rs.getString("nom");
              aff[2] = Rs.getString("thenom");
              aff[3] = Rs.getString("designation");
              aff[4] = Rs.getString("description");
              aff[5] = Rs.getString("prix");
              aff[6] = Rs.getString("dateV");
              mod.addRow(aff);
            }
            table.setModel(mod);
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void deplace(int i){
   try{
     txtid.setText(model.getValueAt(i, 0).toString());
     txtclient.setText(model.getValueAt(i, 1).toString());
     txtproduit.setText(model.getValueAt(i, 3).toString());
     txtdesc.setText(model.getValueAt(i, 4).toString());
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}

private void searchun(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtclient.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from clients where nom like '%"+search+"%'");
        while(Rs.next()){
            cmylist.addItem(Rs.getString("nom"));
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void rsearchun(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtclient.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from clients where nom like '%"+search+"%'");
        while(Rs.next()){
            cmylist.add(Rs.getString("nom"));
            cmylist.removeAll();
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void getIDun() 
    {
        try 
        {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select id from clients where nom='" + cmylist.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next())
            {
                txtidclient.setText(rs.getString("id"));
            }
        } 
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(this, e);
        }
    }    

private void searchdeux(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtproduit.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from articles where designation like '%"+search+"%'");
        while(Rs.next()){
            pmylist.addItem(Rs.getString("designation"));
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void rsearchdeux(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtproduit.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from articles where designation like '%"+search+"%'");
        while(Rs.next()){
            pmylist.add(Rs.getString("designation"));
            pmylist.removeAll();
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void getIDdeux() 
    {
        try 
        {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select id from articles where designation='" + pmylist.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next())
            {
                txtidarticle.setText(rs.getString("id"));
            }
        } 
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(this, e);
        }
    }
private void imprimer(){
        Toolkit kit_par_defaut = Toolkit.getDefaultToolkit();
        JFrame j = new JFrame();
        j.add(panrecu);
        PrintJob pj = kit_par_defaut.getPrintJob(j, "Impression", null);
        Graphics g = pj.getGraphics();
        panrecu.printAll(g);
        pj.end();
}
    private void callrec(){
        try {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select * from vventes where id= '" + txtid.getText() + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next())
            {
                String theid = rs.getString("id");
                String nom = rs.getString("nom");
                String contact = rs.getString("contact");
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMMMMMMM yyyy");
                Date ladate = rs.getDate("dateV");
                String datV = dateFormat.format(ladate);
                String art = rs.getString("designation");
                String leprix = rs.getString("prix");
                
                recutxtid.setText("0"+theid);
                recutxtclient.setText(": "+nom);
                recutxtcontact.setText(": "+contact);
                recutxtart.setText(": "+art);
                recutxtprix.setText(": "+leprix+" $");
                recutxtdate.setText(": "+datV);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        callcb();
}
    @SuppressWarnings("empty-statement")
    private void callcb(){
    try
        {
            stm = conn.obtenirconnexion().createStatement();
            String mysql = "select * from vventes where id= '" + txtid.getText() + "'";
            ResultSet res = stm.executeQuery(mysql);
            if(res.next())
            {
                String id = res.getString("id");
                String thedesc = res.getString("description");
                int hid = id.hashCode();
                int hdesc = thedesc.hashCode();
                
                Codabar  barcode = new Codabar();
                barcode.setData(""+hid+hdesc);
                barcode.setProcessTilde(true);
                barcode.setUom(IBarcode.UOM_PIXEL);
                barcode.setX(2f);
                barcode.setY(25f);
                barcode.setLeftMargin(0f);
                barcode.setRightMargin(0f);
                barcode.setTopMargin(2f);
                barcode.setBottomMargin(0f);
                barcode.setResolution(300);
                barcode.setShowText(true);
                barcode.setTextMargin(3);
                barcode.setRotate(IBarcode.ROTATE_0);
                
                int a = Integer.parseInt(txtid.getText());
                while(a<0);
                String adresse = "C:\\Users\\Public\\Recu"+a+".png";
                barcode.drawBarcode(adresse);
                ImageIcon imgThisImg = new ImageIcon(adresse);
                recuImgCb.setIcon(imgThisImg);
            }
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panclient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panbtns = new javax.swing.JPanel();
        btnupdate = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JLabel();
        btnadd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtidarticle = new javax.swing.JTextField();
        txtproduit = new javax.swing.JTextField();
        txtclient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtidclient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pmylist = new java.awt.List();
        cmylist = new java.awt.List();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        panrecu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        recutxtprix = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        recuImgCb = new javax.swing.JLabel();
        recutxtart = new javax.swing.JLabel();
        recutxtid = new javax.swing.JLabel();
        recutxtdate = new javax.swing.JLabel();
        recutxtclient = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        recutxtcontact = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bacpic = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1460, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panclient.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("VENTES");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("ID");

        panbtns.setBackground(new java.awt.Color(102, 0, 102));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_48.png"))); // NOI18N
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_48.png"))); // NOI18N
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_refresh_48.png"))); // NOI18N
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_48.png"))); // NOI18N
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRINT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnsLayout = new javax.swing.GroupLayout(panbtns);
        panbtns.setLayout(panbtnsLayout);
        panbtnsLayout.setHorizontalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panbtnsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(panbtnsLayout.createSequentialGroup()
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panbtnsLayout.createSequentialGroup()
                        .addGroup(panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate)
                            .addComponent(btndelete))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panbtnsLayout.setVerticalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("ID CLIENT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("DESCRIPTION");

        txtdesc.setColumns(20);
        txtdesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(102, 0, 102));
        txtdesc.setRows(5);
        jScrollPane2.setViewportView(txtdesc);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("PRODUIT");

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(102, 0, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("ID PRODUIT");

        txtidarticle.setEditable(false);
        txtidarticle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtidarticle.setForeground(new java.awt.Color(102, 0, 102));

        txtproduit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtproduit.setForeground(new java.awt.Color(102, 0, 102));
        txtproduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtproduitKeyReleased(evt);
            }
        });

        txtclient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtclient.setForeground(new java.awt.Color(102, 0, 102));
        txtclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclientActionPerformed(evt);
            }
        });
        txtclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtclientKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("CLIENT");

        txtidclient.setEditable(false);
        txtidclient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtidclient.setForeground(new java.awt.Color(102, 0, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("PRODUITS");

        pmylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmylistMouseClicked(evt);
            }
        });
        pmylist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pmylistItemStateChanged(evt);
            }
        });

        cmylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmylistMouseClicked(evt);
            }
        });
        cmylist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmylistItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("CLIENTS");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("RECHERCHE");

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 0, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        panrecu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("EASY-KIVU");
        panrecu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        recutxtprix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtprix.setText("0");
        panrecu.add(recutxtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Prix");
        panrecu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("RECU DE PAIEMENT ");
        panrecu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Client");
        panrecu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Article");
        panrecu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, -1));

        recuImgCb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recuImgCb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recuImgCb.setText("code barre");
        panrecu.add(recuImgCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, 240, 50));

        recutxtart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtart.setText("0");
        panrecu.add(recutxtart, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, -1));

        recutxtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtid.setText("0");
        panrecu.add(recutxtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, -1));

        recutxtdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtdate.setText("0");
        panrecu.add(recutxtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        recutxtclient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtclient.setText("0");
        panrecu.add(recutxtclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Contact");
        panrecu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        recutxtcontact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recutxtcontact.setText("0");
        panrecu.add(recutxtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Date");
        panrecu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        javax.swing.GroupLayout panclientLayout = new javax.swing.GroupLayout(panclient);
        panclient.setLayout(panclientLayout);
        panclientLayout.setHorizontalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2))
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(4, 4, 4)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidarticle))
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtidclient, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtclient, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2))))
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panclientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panclientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsearch)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panclientLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panclientLayout.createSequentialGroup()
                                .addComponent(pmylist, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmylist, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16)))
                .addComponent(panbtns, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panrecu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        panclientLayout.setVerticalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panbtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panclientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panrecu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtid)
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addComponent(txtidclient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtidarticle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panclientLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(7, 7, 7)
                                        .addComponent(txtclient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pmylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsearch)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        add(panclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 860, 250));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 860, 170));

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (425).jpg"))); // NOI18N
        add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, 1700, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       try
        {
            int i=table.getSelectedRow();deplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
       getIDun();
       getIDdeux();
       callrec();
    }//GEN-LAST:event_tableMouseClicked

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
       ajouter();
       afficher();
       refresh();
    }//GEN-LAST:event_btnaddMouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        refresh();
        afficher();
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        modifier();
        afficher();
        refresh();
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        supprimer();
        afficher();
        refresh();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void txtclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclientActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void cmylistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmylistItemStateChanged
        getIDun();
    }//GEN-LAST:event_cmylistItemStateChanged

    private void cmylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmylistMouseClicked
        getIDun();
    }//GEN-LAST:event_cmylistMouseClicked

    private void txtclientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclientKeyReleased
        rsearchun();
        searchun();
    }//GEN-LAST:event_txtclientKeyReleased

    private void txtproduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproduitKeyReleased
        rsearchdeux();
        searchdeux();
    }//GEN-LAST:event_txtproduitKeyReleased

    private void pmylistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pmylistItemStateChanged
        getIDdeux();
    }//GEN-LAST:event_pmylistItemStateChanged

    private void pmylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmylistMouseClicked
       getIDdeux();
    }//GEN-LAST:event_pmylistMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        mysearch();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        imprimer();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel btnadd;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel btnrefresh;
    private javax.swing.JLabel btnupdate;
    private java.awt.List cmylist;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panbtns;
    private javax.swing.JPanel panclient;
    private javax.swing.JPanel panrecu;
    private java.awt.List pmylist;
    private javax.swing.JLabel recuImgCb;
    private javax.swing.JLabel recutxtart;
    private javax.swing.JLabel recutxtclient;
    private javax.swing.JLabel recutxtcontact;
    private javax.swing.JLabel recutxtdate;
    private javax.swing.JLabel recutxtid;
    private javax.swing.JLabel recutxtprix;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtclient;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidarticle;
    private javax.swing.JTextField txtidclient;
    private javax.swing.JTextField txtproduit;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
