/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
public class panelPersonnel extends javax.swing.JPanel {

    /**
     * Creates new form panelClient
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    String path = null;
    byte[]userimg = null;
    DefaultTableModel model = new DefaultTableModel();

    /**
     *
     */
    public panelPersonnel() {
        initComponents();
        panclient.setBackground(new Color(255,255,255,200));
        panbtns.setBackground(new Color(102,0,102,200));
  
        model.addColumn("Id");
        model.addColumn("Noms");
        model.addColumn("Adresse");
        model.addColumn("Contact");
        model.addColumn("Poste");
        
        
        table.setRowHeight(30);
        table.setShowGrid(true);
        table.setGridColor(new Color(102,0,102));
        table.setSelectionBackground(new Color(102,0,102));
        
        
        try{
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from agents");
        while(Rs.next()){
        model.addRow(new Object[]{
           Rs.getString("id"),
           Rs.getString("nom"),
           Rs.getString("adresse"),
           Rs.getString("contact"),
           Rs.getString("poste"),
           });
           }
        }
        catch(Exception e){
        System.err.println(e);
        }
        table.setModel(model);
        chgcmn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //fonctions
    private void ajouter(){
        String nom = txtnom.getText();
        String adresse = txtadresse.getText();
        String telephone = txtcontact.getText();
        String post = txtidposte.getText();
        /*Icon toff = myimg.getIcon();*/
        String requete = "insert into personnel(nom,adresse,contact,refposte) VALUES ('"+
        nom+"','"+
        adresse+"','"+
        telephone+"','"+
        post+"')";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Cet agent a été bien ajouté");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
}
    private void search(){
     try{
        String [] col = {"Id","Nom", "Adresse", "Contact", "Poste"};
        String [] aff = new String[5];
        DefaultTableModel mod= new DefaultTableModel(null, col);
        stm = conn.obtenirconnexion().createStatement();
        String search = txtsearch.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from agents where id like '%"+search+"%' or nom like '%"+search+"%' or adresse like '%"+search+"%' or contact like '%"+search+"%' or poste like '%"+search+"%' ");
            while(Rs.next()){
              aff[0] = Rs.getString("id");
              aff[1] = Rs.getString("nom");
              aff[2] = Rs.getString("adresse");
              aff[3] = Rs.getString("contact");
              aff[4] = Rs.getString("poste");
              mod.addRow(aff);
            }
            table.setModel(mod);
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelPersonnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refresh(){
        txtnom.setText("");
        txtadresse.setText("");
        txtcontact.setText("");
        txtid.setText("");
        txtsearch.setText("");
    }
    
    private void supprimer(){
        try{
            
            if(JOptionPane.showConfirmDialog(null, "Attention, voulez-vous vraiment faire cette opération de suppression?", "Suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0){
                stm.executeUpdate("Delete From personnel where id = "+txtid.getText());
                afficher();
                JOptionPane.showMessageDialog(null, "L'agent a été bien suprimé");
            }
            afficher();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }
    }
    
    private void modifier(){
    try{
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","Modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            stm.executeUpdate(
                    "UPDATE personnel SET nom='"
                    +txtnom.getText()+
                    "', adresse='"
                    +txtadresse.getText()+
                    "',contact='"+txtcontact.getText()+
                    "',refposte='"+txtidposte.getText()+
                    "' WHERE id="+txtid.getText()
                );
            afficher();
        }
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            afficher();
        }
}
private void afficher(){
 try{
        model.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from agents");
        while(Rs.next())
        {
            model.addRow(new Object[]{
                Rs.getString("id"),
                Rs.getString("nom"),
                Rs.getString("adresse"),
                Rs.getString("contact"),
                Rs.getString("poste"),
            }
            );
           
        }
        }
        catch(Exception e){
            System.err.println(e);
        }
        table.setModel(model);
}

private void chgcmn() {
        try {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select * from architecture order by poste ASC";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                txtposte.addItem(rs.getString("poste"));
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
   
    private void getID() {
    try {
    stm = conn.obtenirconnexion().createStatement();
    String sql = "select * from architecture where poste= '" + txtposte.getSelectedItem() + "'";
    ResultSet rs = stm.executeQuery(sql);
    if (rs.next()) {
    String id = rs.getString("id");
    txtidposte.setText(id);
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, e);
    }
    }
private void afficheImg(){
    /*try{
    stm = conn.obtenirconnexion().createStatement();
    ResultSet Rs = stm.executeQuery("Select * from personnel where id = "+txtid.getText());
    while(Rs.next())
    {
    ImageIcon monico = new ImageIcon(Rs.getString("photo"));
    Icon ico = monico;
    myimg.removeAll();
    myimg.setIcon(ico);
    myimg.repaint();
    myimg.revalidate();
    }
    }
    catch(Exception e){
    System.err.println(e);
    }*/
}

private void deplace(int i){
   try{
     txtid.setText(model.getValueAt(i, 0).toString());
     txtnom.setText(model.getValueAt(i, 1).toString());
     txtadresse.setText(model.getValueAt(i, 2).toString());
     txtcontact.setText(model.getValueAt(i, 3).toString());
     
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panclient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtposte = new javax.swing.JComboBox();
        txtidposte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        panbtns = new javax.swing.JPanel();
        btnupdate = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JLabel();
        btnrefresh1 = new javax.swing.JLabel();
        pansearch = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bacpic = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1460, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panclient.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("PERSONNEL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("NOMS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("ID");

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(102, 0, 102));

        txtnom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnom.setForeground(new java.awt.Color(102, 0, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("ADRESSE");

        txtadresse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadresse.setForeground(new java.awt.Color(102, 0, 102));

        txtcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(102, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("CONTACT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("POSTE");

        txtposte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtposteItemStateChanged(evt);
            }
        });
        txtposte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtposteMouseClicked(evt);
            }
        });
        txtposte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtposteActionPerformed(evt);
            }
        });

        txtidposte.setEditable(false);
        txtidposte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtidposte.setForeground(new java.awt.Color(102, 0, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("ID POSTE");

        panbtns.setBackground(new java.awt.Color(102, 0, 102));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_48.png"))); // NOI18N
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_48.png"))); // NOI18N
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_refresh_48.png"))); // NOI18N
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });

        btnrefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_48.png"))); // NOI18N
        btnrefresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefresh1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnsLayout = new javax.swing.GroupLayout(panbtns);
        panbtns.setLayout(panbtnsLayout);
        panbtnsLayout.setHorizontalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnrefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panbtnsLayout.setVerticalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("RECHERCHER");

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 0, 102));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pansearchLayout = new javax.swing.GroupLayout(pansearch);
        pansearch.setLayout(pansearchLayout);
        pansearchLayout.setHorizontalGroup(
            pansearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pansearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsearch)
                .addContainerGap())
            .addGroup(pansearchLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pansearchLayout.setVerticalGroup(
            pansearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pansearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panclientLayout = new javax.swing.GroupLayout(panclient);
        panclient.setLayout(panclientLayout);
        panclientLayout.setHorizontalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtidposte, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtposte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panbtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panclientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panclientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88))
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtcontact))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtadresse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnom)
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addComponent(pansearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panclientLayout.setVerticalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtposte))
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidposte, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panbtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pansearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(panclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 380));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 570, 380));

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (425).jpg"))); // NOI18N
        add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, 1700, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       try
        {
            int i=table.getSelectedRow();deplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
       afficheImg();
    }//GEN-LAST:event_tableMouseClicked

    private void btnrefresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefresh1MouseClicked
       ajouter();
       afficher();
       refresh();
    }//GEN-LAST:event_btnrefresh1MouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        refresh();
        afficher();
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        modifier();
        afficher();
        refresh();
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        supprimer();
        afficher();
        refresh();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        search();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtposteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtposteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtposteActionPerformed

    private void txtposteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtposteItemStateChanged
       getID();
    }//GEN-LAST:event_txtposteItemStateChanged

    private void txtposteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtposteMouseClicked
        getID();
    }//GEN-LAST:event_txtposteMouseClicked

    /*public void monImage(){
    JFileChooser photo = new JFileChooser();
    photo.showOpenDialog(null);
    
    File picture = photo.getSelectedFile();
    path = picture.getAbsolutePath();
    BufferedImage img;
    try{
    img = ImageIO.read(photo.getSelectedFile());
    ImageIcon imageico = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(240, 255, Image.SCALE_AREA_AVERAGING));
    myimg.setIcon(imageico);
    File image = new File(path);
    FileInputStream fis = new FileInputStream(image);
    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    
    }
    catch(Exception e){
    e.printStackTrace();
    }
    
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel btnrefresh;
    private javax.swing.JLabel btnrefresh1;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panbtns;
    private javax.swing.JPanel panclient;
    private javax.swing.JPanel pansearch;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidposte;
    private javax.swing.JTextField txtnom;
    private javax.swing.JComboBox txtposte;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
