/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.codes;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karma03
 */
public class panelArticle extends javax.swing.JPanel {

    /**
     * Creates new form panelClient
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();

    /**
     *
     */
    public panelArticle() {
        initComponents();
        panclient.setBackground(new Color(255,255,255,200));
        panbtns.setBackground(new Color(102,0,102,200));
        panother.setBackground(new Color(255,255,255,50));
        
        model.addColumn("Id");
        model.addColumn("Designation");
        model.addColumn("Prix");
        model.addColumn("Description");
        model.addColumn("Fournisseur");
        
        table.setRowHeight(30);
        table.setShowGrid(true);
        table.setGridColor(new Color(102,0,102));
        table.setSelectionBackground(new Color(102,0,102));
        
        
        try{
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from artfn");
        while(Rs.next()){
        model.addRow(new Object[]{
           Rs.getString("id"),
           Rs.getString("designation"),
           Rs.getString("prix"),
           Rs.getString("description"),
           Rs.getString("thenom")
           });
           }
        }
        catch(Exception e){
        System.err.println(e);
        }
        table.setModel(model);
        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //fonctions
    private void ajouter(){
        String designat = txtdesignation.getText();
        String foun = txtidfoun.getText();
        String price = txtprix.getText();
        String desc = txtdesc.getText();
        String requete = "insert into articles(designation,prix,fourn,description) VALUES ('"+
        designat+"','"+
        price+"','"+
        foun+"','"+
        desc+"')";
        try{
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Le produit a été bien ajouté");
        }
        catch(SQLException | HeadlessException ex){JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());}
}
    
    
    private void refresh(){
        txtdesignation.setText("");
        txtidfoun.setText("");
        txtprix.setText("");
        txtid.setText("");
        txtdesc.setText("");
        txtfoun.setText("");
    }
    
    private void supprimer(){
        try{
            
            if(JOptionPane.showConfirmDialog(null, "Attention, voulez-vous vraiment faire cette opération de suppression?", "Suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            if(txtid.getText().length()!=0){
                stm.executeUpdate("Delete From articles where id = "+txtid.getText());
                afficher();
                JOptionPane.showMessageDialog(null, "Le produit a été bien suprimé");
            }
            afficher();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suppression"+e.getMessage());
        }
    }
    
    private void modifier(){
    try{
            if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","Modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
            stm.executeUpdate(
                    "UPDATE articles SET designation='"
                    +txtdesignation.getText()+
                    "', fourn='"
                    +txtidfoun.getText()+
                    "',prix='"+txtprix.getText()+
                    "',description='"+txtdesc.getText()+
                    "' WHERE id="+txtid.getText()
                );
            afficher();
        }
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur de modification"+e.getMessage());
            System.err.println(e);
            afficher();
        }
}
private void afficher(){
 try{
        model.setRowCount(0);
        stm = conn.obtenirconnexion().createStatement();
        ResultSet Rs = stm.executeQuery("Select * from artfn");
        while(Rs.next())
        {
            model.addRow(new Object[]{
                Rs.getString("id"),
                Rs.getString("designation"),
                Rs.getString("prix"),
                Rs.getString("description"),
                Rs.getString("thenom")
            }
            );
        }
        }
        catch(Exception e){
            System.err.println(e);
        }
        table.setModel(model);
}

private void mysearch(){
     try{
        String [] col = {"Id","Designation", "Prix", "Description", "Fournisseur"};
        String [] aff = new String[5];
        DefaultTableModel mod= new DefaultTableModel(null, col);
        stm = conn.obtenirconnexion().createStatement();
        String search = txtsearch.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from artfn where id like '%"+search+"%' or designation like '%"+search+"%' or prix like '%"+search+"%' or description like '%"+search+"%' or thenom like '%"+search+"%' ");
            while(Rs.next()){
              aff[0] = Rs.getString("id");
              aff[1] = Rs.getString("designation");
              aff[2] = Rs.getString("prix");
              aff[3] = Rs.getString("description");
              aff[4] = Rs.getString("thenom");
              mod.addRow(aff);
            }
            table.setModel(mod);
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void deplace(int i){
   try{
     txtid.setText(model.getValueAt(i, 0).toString());
     txtdesignation.setText(model.getValueAt(i, 1).toString());
     txtprix.setText(model.getValueAt(i, 2).toString());
     txtdesc.setText(model.getValueAt(i, 3).toString());
     txtfoun.setText(model.getValueAt(i, 4).toString());
     
   }
   catch(Exception e)
   {
       System.err.println(e);
       JOptionPane.showMessageDialog(null, "Erreur de deplacement"+e.getLocalizedMessage());
   }
}

private void search(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtfoun.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from fournisseurs where thenom like '%"+search+"%' order by thenom ASC");
        while(Rs.next()){
            mylist.addItem(Rs.getString("thenom"));
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void rsearch(){
     try{
        stm = conn.obtenirconnexion().createStatement();
        String search = txtfoun.getText();
        ResultSet Rs = null;
        Rs = stm.executeQuery("Select * from fournisseurs where thenom like '%"+search+"%' order by thenom ASC");
        while(Rs.next()){
            mylist.addItem(Rs.getString("thenom"));
            mylist.removeAll();
        }
        
     } 
     catch (SQLException ex) {
            Logger.getLogger(panelFournisseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void getID() 
    {
        try 
        {
            stm = conn.obtenirconnexion().createStatement();
            String sql = "select id from fournisseurs where thenom='" + mylist.getSelectedItem()+ "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next())
            {
                txtidfoun.setText(rs.getString("id"));
            }
        } 
        catch (Exception e) 
        {
        JOptionPane.showMessageDialog(this, e);
        }
    }    


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panclient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panbtns = new javax.swing.JPanel();
        btnupdate = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JLabel();
        btnrefresh1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        txtfoun = new javax.swing.JTextField();
        txtidfoun = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        txtdesignation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        mylist = new java.awt.List();
        panother = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bacpic = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1460, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panclient.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("FOURNISSEUR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("ARTICLES");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("DESIGNATION");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("PRIX");

        panbtns.setBackground(new java.awt.Color(102, 0, 102));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_48.png"))); // NOI18N
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_48.png"))); // NOI18N
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_refresh_48.png"))); // NOI18N
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });

        btnrefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_48.png"))); // NOI18N
        btnrefresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefresh1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panbtnsLayout = new javax.swing.GroupLayout(panbtns);
        panbtns.setLayout(panbtnsLayout);
        panbtnsLayout.setHorizontalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnrefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panbtnsLayout.setVerticalGroup(
            panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panbtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panbtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrefresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("ID FOURNISSEUR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("DESCRIPTION");

        txtdesc.setColumns(20);
        txtdesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(102, 0, 102));
        txtdesc.setRows(5);
        jScrollPane2.setViewportView(txtdesc);

        txtfoun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtfoun.setForeground(new java.awt.Color(102, 0, 102));
        txtfoun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfounKeyReleased(evt);
            }
        });

        txtidfoun.setEditable(false);
        txtidfoun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtidfoun.setForeground(new java.awt.Color(102, 0, 102));

        txtprix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprix.setForeground(new java.awt.Color(102, 0, 102));

        txtdesignation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdesignation.setForeground(new java.awt.Color(102, 0, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("ID");

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout panclientLayout = new javax.swing.GroupLayout(panclient);
        panclient.setLayout(panclientLayout);
        panclientLayout.setHorizontalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdesignation)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(panclientLayout.createSequentialGroup()
                                    .addComponent(txtfoun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtidfoun, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panclientLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(97, 97, 97)))
                            .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane2)
                                .addComponent(panbtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panclientLayout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(jLabel5)))
                            .addGroup(panclientLayout.createSequentialGroup()
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtprix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panclientLayout.setVerticalGroup(
            panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panclientLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfoun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidfoun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panbtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(panclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 420));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 570, 250));

        mylist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mylist.setForeground(new java.awt.Color(102, 0, 102));
        mylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mylistMouseClicked(evt);
            }
        });
        mylist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mylistItemStateChanged(evt);
            }
        });
        add(mylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 280, 160));

        panother.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VERY EASY, VERY SPEED");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EASY KIVU");

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 0, 102));
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Recherche");

        javax.swing.GroupLayout panotherLayout = new javax.swing.GroupLayout(panother);
        panother.setLayout(panotherLayout);
        panotherLayout.setHorizontalGroup(
            panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panotherLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(95, 95, 95))))
        );
        panotherLayout.setVerticalGroup(
            panotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panotherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(23, 23, 23))
        );

        add(panother, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 280, 160));

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Best Pictures/design (425).jpg"))); // NOI18N
        add(bacpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, 1700, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       try
        {
            int i=table.getSelectedRow();deplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Erreur de deplacement"+e.getLocalizedMessage());}
       getID();
    }//GEN-LAST:event_tableMouseClicked

    private void btnrefresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefresh1MouseClicked
       ajouter();
       afficher();
       refresh();
    }//GEN-LAST:event_btnrefresh1MouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        refresh();
        afficher();
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        modifier();
        afficher();
        refresh();
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        supprimer();
        afficher();
        refresh();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void mylistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mylistItemStateChanged
        getID();
    }//GEN-LAST:event_mylistItemStateChanged

    private void mylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mylistMouseClicked
        getID();
    }//GEN-LAST:event_mylistMouseClicked

    private void txtfounKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfounKeyReleased
        rsearch();
        search();
    }//GEN-LAST:event_txtfounKeyReleased

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        mysearch();
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bacpic;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel btnrefresh;
    private javax.swing.JLabel btnrefresh1;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.List mylist;
    private javax.swing.JPanel panbtns;
    private javax.swing.JPanel panclient;
    private javax.swing.JPanel panother;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtfoun;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidfoun;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
